# Generated by Django 3.2.4 on 2021-07-04 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20210703_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='date_taken',
            field=models.DateField(blank=True, default=datetime.date(2021, 7, 4)),
        ),
    ]
