# Generated by Django 3.2.4 on 2021-07-06 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_alter_image_date_taken'),
    ]

    operations = [
        migrations.CreateModel(
            name='NesletterSubscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='date_taken',
            field=models.DateField(blank=True, default=datetime.date(2021, 7, 6)),
        ),
    ]
