# Generated by Django 3.2.5 on 2021-07-07 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_auto_20210706_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='date_taken',
            field=models.DateField(blank=True, default=datetime.date(2021, 7, 7)),
        ),
    ]
